/* WonderSprout page copy — K layer, part 2: promise chips + shared messages, all 21 languages. */
(function () {
  "use strict";
  if (typeof WSI18n === "undefined") return;

  const K = {
en: {"pr.c1":"No ads — ever","pr.c2":"No child rankings","pr.c3":"No diagnosis","pr.c4":"Minimal data","pr.c5":"Parent-controlled","p.welcomeSync":"Welcome! ","p.welcomeSync2":"'s wonders now sync to the cloud ☁️","x.noSpeech":"Read-aloud needs a browser with speech support 🔇"},
ar: {"pr.c1":"بلا إعلانات — أبدًا","pr.c2":"بلا تصنيف للأطفال","pr.c3":"بلا تشخيص","pr.c4":"أقل قدر من البيانات","pr.c5":"بتحكم الأهل","p.welcomeSync":"أهلًا! ","p.welcomeSync2":" — عجائبه تُزامَن الآن مع السحابة ☁️","x.noSpeech":"القراءة الجهرية تحتاج متصفحًا يدعم النطق 🔇"},
zh: {"pr.c1":"永无广告","pr.c2":"不给孩子排名","pr.c3":"不做诊断","pr.c4":"数据最少","pr.c5":"家长掌控","p.welcomeSync":"欢迎！","p.welcomeSync2":" 的奇想现在会同步到云端 ☁️","x.noSpeech":"朗读需要支持语音的浏览器 🔇"},
es: {"pr.c1":"Sin anuncios — nunca","pr.c2":"Sin rankings de niños","pr.c3":"Sin diagnósticos","pr.c4":"Datos mínimos","pr.c5":"Control de los padres","p.welcomeSync":"¡Bienvenido! ","p.welcomeSync2":": sus maravillas ya se sincronizan con la nube ☁️","x.noSpeech":"La lectura en voz alta necesita un navegador con voz 🔇"},
fr: {"pr.c1":"Sans pub — jamais","pr.c2":"Pas de classement d'enfants","pr.c3":"Pas de diagnostic","pr.c4":"Données minimales","pr.c5":"Contrôlé par les parents","p.welcomeSync":"Bienvenue ! ","p.welcomeSync2":" — ses merveilles se synchronisent maintenant ☁️","x.noSpeech":"La lecture à voix haute exige un navigateur avec synthèse vocale 🔇"},
de: {"pr.c1":"Keine Werbung — nie","pr.c2":"Keine Kinderrankings","pr.c3":"Keine Diagnosen","pr.c4":"Minimale Daten","pr.c5":"Von Eltern kontrolliert","p.welcomeSync":"Willkommen! ","p.welcomeSync2":"s Wunder werden jetzt mit der Cloud synchronisiert ☁️","x.noSpeech":"Vorlesen braucht einen Browser mit Sprachausgabe 🔇"},
pt: {"pr.c1":"Sem anúncios — nunca","pr.c2":"Sem rankings de crianças","pr.c3":"Sem diagnósticos","pr.c4":"Dados mínimos","pr.c5":"Controlado pelos pais","p.welcomeSync":"Bem-vindo! ","p.welcomeSync2":" — as maravilhas agora sincronizam com a nuvem ☁️","x.noSpeech":"A leitura em voz alta precisa de um navegador com voz 🔇"},
ru: {"pr.c1":"Без рекламы — никогда","pr.c2":"Без рейтингов детей","pr.c3":"Без диагнозов","pr.c4":"Минимум данных","pr.c5":"Под контролем родителей","p.welcomeSync":"Добро пожаловать! ","p.welcomeSync2":" — чудеса теперь синхронизируются с облаком ☁️","x.noSpeech":"Для чтения вслух нужен браузер с синтезом речи 🔇"},
hi: {"pr.c1":"कोई विज्ञापन नहीं — कभी नहीं","pr.c2":"बच्चों की रैंकिंग नहीं","pr.c3":"कोई निदान नहीं","pr.c4":"न्यूनतम डेटा","pr.c5":"अभिभावक के नियंत्रण में","p.welcomeSync":"स्वागत! ","p.welcomeSync2":" के अचरज अब क्लाउड से सिंक होते हैं ☁️","x.noSpeech":"पढ़कर सुनाने के लिए वाणी-समर्थ ब्राउज़र चाहिए 🔇"},
ur: {"pr.c1":"کوئی اشتہار نہیں — کبھی نہیں","pr.c2":"بچوں کی درجہ بندی نہیں","pr.c3":"کوئی تشخیص نہیں","pr.c4":"کم سے کم ڈیٹا","pr.c5":"والدین کے کنٹرول میں","p.welcomeSync":"خوش آمدید! ","p.welcomeSync2":" کے عجائبات اب کلاؤڈ سے ہم آہنگ ہوتے ہیں ☁️","x.noSpeech":"بلند آواز میں پڑھنے کے لیے آواز کی سہولت والا براؤزر درکار ہے 🔇"},
tr: {"pr.c1":"Reklam yok — asla","pr.c2":"Çocuk sıralaması yok","pr.c3":"Tanı koyma yok","pr.c4":"En az veri","pr.c5":"Ebeveyn kontrolünde","p.welcomeSync":"Hoş geldin! ","p.welcomeSync2":" — harikalar artık buluta senkron ☁️","x.noSpeech":"Sesli okuma için konuşma destekli bir tarayıcı gerekir 🔇"},
id: {"pr.c1":"Tanpa iklan — selamanya","pr.c2":"Tanpa peringkat anak","pr.c3":"Tanpa diagnosis","pr.c4":"Data minimal","pr.c5":"Dikendalikan orang tua","p.welcomeSync":"Selamat datang! ","p.welcomeSync2":" — keajaibannya kini tersinkron ke cloud ☁️","x.noSpeech":"Membaca nyaring perlu browser dengan dukungan suara 🔇"},
sw: {"pr.c1":"Hakuna matangazo — milele","pr.c2":"Hakuna viwango vya watoto","pr.c3":"Hakuna utambuzi wa magonjwa","pr.c4":"Data chache","pr.c5":"Chini ya udhibiti wa mzazi","p.welcomeSync":"Karibu! ","p.welcomeSync2":" — maajabu yake sasa yanasawazishwa kwenye wingu ☁️","x.noSpeech":"Kusoma kwa sauti kunahitaji kivinjari chenye sauti 🔇"},
it: {"pr.c1":"Niente pubblicità — mai","pr.c2":"Nessuna classifica dei bambini","pr.c3":"Nessuna diagnosi","pr.c4":"Dati minimi","pr.c5":"Controllato dai genitori","p.welcomeSync":"Benvenuto! ","p.welcomeSync2":" — le sue meraviglie ora si sincronizzano ☁️","x.noSpeech":"La lettura ad alta voce richiede un browser con sintesi vocale 🔇"},
nl: {"pr.c1":"Geen ads — nooit","pr.c2":"Geen kinderranglijsten","pr.c3":"Geen diagnoses","pr.c4":"Minimale data","pr.c5":"Oudercontrole","p.welcomeSync":"Welkom! ","p.welcomeSync2":" — wonderen synchroniseren nu met de cloud ☁️","x.noSpeech":"Hardop voorlezen heeft een browser met spraak nodig 🔇"},
ja: {"pr.c1":"こうこくは ありません — えいえんに","pr.c2":"こどもの ランキング なし","pr.c3":"しんだん しません","pr.c4":"データは さいしょう","pr.c5":"おやが かんり","p.welcomeSync":"ようこそ！","p.welcomeSync2":" の ふしぎが クラウドと どうき されます ☁️","x.noSpeech":"よみあげには おんせい たいおうの ブラウザが ひつようです 🔇"},
ko: {"pr.c1":"광고 없음 — 영원히","pr.c2":"아이 순위 없음","pr.c3":"진단 없음","pr.c4":"최소 데이터","pr.c5":"학부모가 통제","p.welcomeSync":"환영해요! ","p.welcomeSync2":"의 놀라움이 이제 클라우드와 동기화돼요 ☁️","x.noSpeech":"소리 내어 읽기에는 음성 지원 브라우저가 필요해요 🔇"},
bn: {"pr.c1":"কোনো বিজ্ঞাপন নেই — কখনো না","pr.c2":"শিশুদের র‍্যাংকিং নেই","pr.c3":"কোনো রোগনির্ণয় নেই","pr.c4":"ন্যূনতম ডেটা","pr.c5":"অভিভাবকের নিয়ন্ত্রণে","p.welcomeSync":"স্বাগতম! ","p.welcomeSync2":"-এর বিস্ময় এখন ক্লাউডে সিঙ্ক হয় ☁️","x.noSpeech":"জোরে পড়তে স্পিচ সাপোর্টসহ ব্রাউজার লাগবে 🔇"},
yo: {"pr.c1":"Kò sí ìpolongo — rárá","pr.c2":"Kò sí ìdíyelé ọmọ","pr.c3":"Kò sí ìwádìí àìsàn","pr.c4":"Ìwífún kékeré","pr.c5":"Ìdarí òbí","p.welcomeSync":"Ẹ kú àbọ̀! ","p.welcomeSync2":" — àwọn ìyanu rẹ̀ ń bá ojú òfuurufú mu ☁️","x.noSpeech":"Kíkà gbangba nílò aṣàwákiri tí ó ní ohùn 🔇"},
ha: {"pr.c1":"Babu talla — tabbatacce","pr.c2":"Babu matsayi na yara","pr.c3":"Babu gano cuta","pr.c4":"Bayanai kaɗan","pr.c5":"Iyayen ke sarrafawa","p.welcomeSync":"Barka da zuwa! ","p.welcomeSync2":" — abubuwan mamakinsa yanzu suna aiki tare da gajimare ☁️","x.noSpeech":"Karatu da murya yana buƙatar mai bincike mai murya 🔇"},
ig: {"pr.c1":"Enweghị mgbasa ozi — ma ọlị","pr.c2":"Enweghị ọkwa ụmụaka","pr.c3":"Enweghị nchọpụta ọrịa","pr.c4":"Data dị ntakịrị","pr.c5":"Nne na nna na-achịkwa","p.welcomeSync":"Nnọọ! ","p.welcomeSync2":" — ebube ya na-emekọrịta na igwe ojii ☁️","x.noSpeech":"Ịgụ n'olu dara ụda chọrọ ihe nchọgharị nwere olu 🔇"},
  };

  for (const code in K) WSI18n.kextend(code, K[code]);
})();
